import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const satoshi = localFont({
  src: "./assets/fonts/Satoshi/Satoshi-Variable.woff2",
  display: "swap",
  style: "normal",
  variable: "--font-satoshi",
});
const clash_display = localFont({
  src: "./assets/fonts/ClashDisplay/ClashDisplay-Variable.woff2",
  display: "swap",
  style: "normal",
  variable: "--font-clash-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${clash_display.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
